class PracticumApiErrorException(Exception):
    '''Вызывается при ошибках в работе API практикума'''
    pass
